version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - cd languages/python
      - bin/build
      - cd .infrastructure
      - npx cdk deploy "*--layers--*"
